version: '3.8'

services:
  messagesilo:
    image: messagesilo
    ports:
      - "5000:80"
    environment:
      PrimarySiloAddress: "127.0.0.1"
      StateUnlockerKey: "test"
      DatabaseConnectionString: "mongodb://database:27017"
      DatabaseName: "messagesilo-local"
      AIApiKey: ""
      AppInsightsConnectionString: ""
    build:
      context: .
      dockerfile: src/MessageSilo/Dockerfile
    depends_on:
      - database

  database:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes: 
      - ~/mongo/data:/data/db
