version: '3.4'

services:
  messagesilo.influxdb:
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=YouAreNotPrepared!
      - DOCKER_INFLUXDB_INIT_ORG=MessageSilo
      - DOCKER_INFLUXDB_INIT_BUCKET=DeadLetteredMessages
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=local-test
    volumes:
      - "${APPDATA}/Microsoft/UserSecrets/messagerepo:/var/lib/influxdb2" 
  messagesilo.silo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  messagesilo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro