name: API

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "scripts/**"

jobs:
  steps:
    environment: prd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Build
        working-directory: ./src/MessageSilo.API
        run: dotnet build

      - name: Publish
        working-directory: ./src/MessageSilo.API
        run: dotnet publish -c Release -o "/home/runner/work/MessageSilo/publish"

      - name: Transform appsettings
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '$('
          tokenSuffix: ')'
          files: '["**/appsettings.js"]'
        env:
          ConnectionStrings.AI: ${{ secrets.CONNECTIONSTRINGS_AI }}
          ConnectionStrings.GrainStateStorage: ${{ secrets.CONNECTIONSTRINGS_GRAINSTATESTORAGE }}

      - name: Upload build artifact
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.U }}
          password: ${{ secrets.P }}
          port: ${{ secrets.PORT }}
          local: /home/runner/work/MessageSilo/publish
          remote: /home/temp/api
