name: Message Silo

on: workflow_dispatch

jobs:
  steps:
    environment: prd
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_S }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
            resource-group: message-silo-prd-rg-sponsor
            dns-name-label: message-silo
            image: berkid89/messagesilo:latest
            name: message-silo-prd-aci
            location: 'westeurope'
            cpu: 1
            memory: 2