name: Message Silo

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "scripts/**"

jobs:
  steps:
    environment: prd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        working-directory: ./src/MessageSilo
        run: dotnet build

      - name: Publish
        working-directory: ./src/MessageSilo
        run: dotnet publish -c Release -o "/home/runner/work/MessageSilo/publish"

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: src/MessageSilo/Dockerfile
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/messagesilo:latest,${{ secrets.DOCKERHUB_USERNAME }}/messagesilo:1.2.${{ github.run_number }}"