name: Silo

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "scripts/**"

jobs:
  steps:
    environment: prd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Transform appsettings
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '$('
          tokenSuffix: ')'
          files: '["**/appsettings.json"]'
        env:
          PrimarySiloAddress: 127.0.0.1
          StateUnlockerKey: ${{ secrets.ORLEANS_STATEUNLOCKERKEY }}
          DatabaseConnectionString: ${{ secrets.DATABASECONNECTIONSTRING }}
          DatabaseName: messagesilo-prd
          AIApiKey: ${{ secrets.AI_APIKEY }}
          AppInsightsConnectionString: ${{ secrets.CONNECTIONSTRINGS_AI }}

      - name: Build
        working-directory: ./src/MessageSilo.Silo
        run: dotnet build

      - name: Publish
        working-directory: ./src/MessageSilo.Silo
        run: dotnet publish -c Release -o "/home/runner/work/MessageSilo/publish"

      - name: Upload build artifact
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.U }}
          password: ${{ secrets.P }}
          port: ${{ secrets.PORT }}
          local: /home/runner/work/MessageSilo/publish
          remote: /home/temp/silo

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: src/MessageSilo.Silo/Dockerfile
          push: true
          tags: "berkid89/messagesilo-silo:latest"