name: siloctl

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      working-directory: ./src/MessageSilo.SiloCTL
      run: dotnet build
    - name: Publish - WINDOWS
      working-directory: ./src/MessageSilo.SiloCTL
      run: dotnet publish -r win-x64 --sc -o "/publish/win-x64"
    - name: Publish - OSX
      working-directory: ./src/MessageSilo.SiloCTL
      run: dotnet publish -r osx-x64 --sc -o "/publish/osx-x64"
    - name: Publish - LINUX
      working-directory: ./src/MessageSilo.SiloCTL
      run: dotnet publish -r linux-x64 --sc -o "/publish/linux-x64"
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ciloctl-artifacts
        path: "./src/MessageSilo.SiloCTL/publish"
