name: siloctl-release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Build
        working-directory: ./src/MessageSilo.SiloCTL
        run: dotnet build

      - name: Publish
        working-directory: ./src/MessageSilo.SiloCTL
        run: dotnet publish -c Release --sc -o "/home/runner/work/MessageSilo/publish"

      - name: Create release
        id: siloctl_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First verion
          draft: false
          prerelease: false
