name: siloctl

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      working-directory: ./src/MessageSilo.SiloCTL
      run: dotnet build
     
  approve:
    needs: build
    environment:
      name: approvers
    runs-on: ubuntu-latest
    steps:
    - name: Manual Approve
      run: |
        echo "Approved"
        
  publish:  
    runs-on: ubuntu-latest
    steps: 
    - name: Publish - WINDOWS
      working-directory: ./src/MessageSilo.SiloCTL
      run: dotnet publish -c Release -r win-x64 --sc -o "/home/runner/work/MessageSilo/publish/win-x64"
    - name: Publish - OSX
      working-directory: ./src/MessageSilo.SiloCTL
      run: dotnet publish -c Release -r osx-x64 --sc -o "/home/runner/work/MessageSilo/publish/osx-x64"
    - name: Publish - LINUX
      working-directory: ./src/MessageSilo.SiloCTL
      run: dotnet publish -c Release -r linux-x64 --sc -o "/home/runner/work/MessageSilo/publish/linux-x64"
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ciloctl-artifacts
        path: "/home/runner/work/MessageSilo/publish/*"
