name: siloctl Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/**"
      - "scripts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        working-directory: ./src/MessageSilo.SiloCTL
        run: dotnet build
