name: siloctl-release

on: workflow_dispatch

jobs:
  build-and-publish:
    name: siloctl-1.0.46
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install azure-cli
        uses: pietrobolcato/install-azure-cli-action@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Build
        working-directory: ./src/MessageSilo.SiloCTL
        run: dotnet build -c Release

      - name: Publish - Windows
        working-directory: ./src/MessageSilo.SiloCTL
        run: dotnet publish -c Release --sc -o "/home/runner/work/MessageSilo/publish/win-x64" -p:Version="1.0.46" -r win-x64

      - name: Publish - Linux
        working-directory: ./src/MessageSilo.SiloCTL
        run: dotnet publish -c Release --sc -o "/home/runner/work/MessageSilo/publish/linux-x64" -p:Version="1.0.46" -r linux-x64

      - name: Publish - MacOS
        working-directory: ./src/MessageSilo.SiloCTL
        run: dotnet publish -c Release --sc -o "/home/runner/work/MessageSilo/publish/osx-x64" -p:Version="1.0.46" -r osx-x64

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_O }}

      - name: Upload build artifacts
        working-directory: /home/runner/work/MessageSilo/publish
        run: |
          az storage blob upload-batch --account-name messagesiloreleases -d "siloctl-win-x64" -s "win-x64" --pattern "*" --overwrite true
          az storage blob upload-batch --account-name messagesiloreleases -d "siloctl-linux-x64" -s "linux-x64" --pattern "*" --overwrite true
          az storage blob upload-batch --account-name messagesiloreleases -d "siloctl-osx-x64" -s "osx-x64" --pattern "*" --overwrite true
